In [6]:
import numpy as np
import matplotlib.pyplot as plt
import copy

In [27]:
n = 4
W = 5
J = 1.
H = np.zeros((n,n))
for i in range(n):
    H[i,i] = np.random.uniform(-W,W)
    for j in range(n):
        if np.abs(i-j)==1:
            H[i,j] = J
print(H)
print('Eigenvalues = ',np.linalg.eigh(H)[0])


[[ 2.10801291  1.          0.          0.        ]
 [ 1.          2.93480307  1.          0.        ]
 [ 0.          1.         -3.29904479  1.        ]
 [ 0.          0.          1.          1.20795504]]
Eigenvalues =  [-3.66018585  1.33468276  1.56699762  3.71023171]


In [88]:
def flow(H,dl=10**(-3),steps = 100000):
    H2 = copy.deepcopy(H)
    n,_ = H2.shape
    U = np.identity(n)
    for q in range(steps):
        
        H0 = np.diag(np.diag(H2))
        V = H2-H0
        Vmax = np.max(np.abs(V.reshape(n**2)))

        eta = H0@V - V@H0
        
        U = (np.identity(n) + dl*eta)@U
        
        dH = eta@H2-H2@eta

        H2 += dl*dH
        
    return H2,Vmax,U

In [89]:
Hdiag = flow(H)
print(np.sort(np.diag(Hdiag[0])))
print(Hdiag[1])

[-3.66631128  1.33477905  1.56901423  3.71424424]
0.000985515456995663


In [92]:
U=Hdiag[2]
print(Hdiag[0])
print(U@H@(U.T))

[[ 1.56901423e+000  3.85539486e-202  8.89318163e-323 -9.85461386e-004]
 [ 3.85539486e-202  3.71424424e+000 -4.44659081e-323 -7.22275146e-205]
 [ 8.89318163e-323 -4.44659081e-323 -3.66631128e+000  9.38724727e-323]
 [-9.85461386e-004 -7.22275146e-205  9.38724727e-323  1.33477905e+000]]
[[ 1.56824176e+00  1.54915547e-03  3.05608842e-04  7.87263184e-04]
 [ 1.54915547e-03  3.71352795e+00  5.16404739e-05 -6.77773748e-04]
 [ 3.05608842e-04  5.16404739e-05 -3.66390339e+00  4.16015034e-04]
 [ 7.87263184e-04 -6.77773748e-04  4.16015034e-04  1.33513687e+00]]


In [95]:
Hdiag2 = U@H@(U.T)
print(np.linalg.eigh(H)[0])
print(np.sort(np.diag(Hdiag[0])))
print(np.sort(np.diag(Hdiag2)))

[-3.66018585  1.33468276  1.56699762  3.71023171]
[-3.66631128  1.33477905  1.56901423  3.71424424]
[-3.66390339  1.33513687  1.56824176  3.71352795]


In [96]:
H4 = np.random.uniform(-W,W,n**4)
H4 = H4.reshape(n,n,n,n)

In [97]:
U2 = np.identity(n)
U4 = np.zeros((n,n,n,n))
for i in range(n):
    for j in range(n):
        U4[i,i,j,j] = 1.0

In [ ]:
def con2(A,B):
    C = np.zeros((n,n,n,n))
    for i in range(n):
        for j in range(n):
            for k in range(n):
                for q in range(n):
                    for p in range(n):
                        C[i,j,k,q] += A[i,p]*